# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'LiuAGeIOS' do
    pod 'SnapKit', '~> 0.21.0'
    pod 'YYWebImage', '~> 1.0.3'
    pod 'SVProgressHUD', '~> 2.0.3'
    pod 'SDCycleScrollView','~> 1.3'
    pod 'Alamofire', '~> 3.4.0'
    pod 'SwiftyJSON', '~> 2.3.2'
    pod 'MJRefresh', '~> 3.1.0'
    pod 'pop', '~> 1.0.9'
    pod 'IQKeyboardManagerSwift'
    pod 'GRMustache.swift', '~> 1.0'
    pod 'CryptoSwift'
  use_frameworks!

  # Pods for LiuAGeIOS

  target 'LiuAGeIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LiuAGeIOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
